[package]
name = "sfcpl2"
version = "0.1.0"
authors = ["Yuta Sadamori <yutapypy0930@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitset = { path = "./crates/bitset" }
brute-bits = { path = "./crates/brute-bits" }
digitex = { path = "./crates/digitex" }
prime = { path = "./crates/prime" }
rle = { path = "./crates/rle" }
unique-count = { path = "./crates/unique-count" }

[dev-dependencies]
rand = "0.8.3"
