[package]
name = "digitex"
version = "0.1.0"
authors = ["Yuta Sadamori <yutapypy0930@gmail.com>"]
description = "convert numbers base and display"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Loptall/sfcpl2"

[features]
atcoder = []

[dependencies]
