[package]
name = "unique-count"
version = "0.1.0"
authors = ["Yuta Sadamori <yutapypy0930@gmail.com>"]
description = "Count the elements in slice"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Loptall/sfcpl2"

[dependencies]
